---

# s3, git, time, github-release, registry-image,
# pool - serialize access to external systems
# git - can also push

resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
#  - name: istio-installer #DO NOT SET TO FORK - for testing use another pipeline and pause this one
#    type: git
#    source:
#      uri: "https://github.com/istio/istio-installer"
#
  - name: istio-master
    type: git
    source:
      uri: "https://github.com/istio/istio"
      branch: master

  - name: istio-installer-pr
    type: pull-request
    source:
        repository: "istio/istio-installer"
        access_token: ((GITHUB_ACCESS_TOKEN))

jobs:
  - name: validate-istio-installer-pr
    serial_groups: [ cluster ]
    plan:
    - get: istio-installer-pr
      trigger: true
    - get: istio-master
      trigger: false
    - put: istio-installer-pr
      params:
        path: istio-installer-pr
        status: pending
    - task: validate
      params:
        KUBECONFIG: ((KUBECONFIG))
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: gcr.io/peripli/istio-base
        inputs:
          - name: istio-installer-pr
          - name: istio-master
        run:
          path: /bin/sh
          args:
          - -ec
          - |
            cd istio-installer-pr
            # HUB=istionightly TAG=nightly-master make run-build
            echo "$KUBECONFIG" > /tmp/kubeconfig.yaml
            export KUBECONFIG=/tmp/kubeconfig.yaml
            kubectl delete namespace istio-system --ignore-not-found
            kubectl apply -k crds
            kubectl apply -k test/demo
            ISTIO_CONTROL=istio-system INGRESS_NS=istio-system bin/test.sh --skip-cleanup ../istio-master
      on_failure:
        put: istio-installer-pr
        params:
          path: istio-installer-pr
          status: failure
    - put: istio-installer-pr
      params:
        path: istio-installer-pr
        status: success

